/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
var Transport_pb = require('./Transport_pb.js');
goog.object.extend(proto, Transport_pb);
var Delivery_pb = require('./Delivery_pb.js');
goog.object.extend(proto, Delivery_pb);
var stores_pb = require('./stores_pb.js');
goog.object.extend(proto, stores_pb);
goog.exportSymbol('proto.OptimizationTask', null, global);
goog.exportSymbol('proto.OptimizationTask.OptimizationTaskStatusEnum', null, global);
goog.exportSymbol('proto.Route', null, global);
goog.exportSymbol('proto.RouteAllResponse', null, global);
goog.exportSymbol('proto.RoutePoint', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Route = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Route.repeatedFields_, null);
};
goog.inherits(proto.Route, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Route.displayName = 'proto.Route';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.RoutePoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.RoutePoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.RoutePoint.displayName = 'proto.RoutePoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.OptimizationTask = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.OptimizationTask.repeatedFields_, null);
};
goog.inherits(proto.OptimizationTask, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.OptimizationTask.displayName = 'proto.OptimizationTask';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.RouteAllResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.RouteAllResponse.repeatedFields_, null);
};
goog.inherits(proto.RouteAllResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.RouteAllResponse.displayName = 'proto.RouteAllResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Route.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.Route.prototype.toObject = function(opt_includeInstance) {
    return proto.Route.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.Route} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.Route.toObject = function(includeInstance, msg) {
    var obj = {
      id: jspb.Message.getFieldWithDefault(msg, 1, 0),
      name: jspb.Message.getFieldWithDefault(msg, 2, ""),
      routerpointsList: jspb.Message.toObjectList(msg.getRouterpointsList(),
          proto.RoutePoint.toObject, includeInstance),
      deliverydate: jspb.Message.getFieldWithDefault(msg, 4, ""),
      optimizationtask: (f = msg.getOptimizationtask()) && proto.OptimizationTask.toObject(includeInstance, f),
      vehicle: (f = msg.getVehicle()) && Transport_pb.Vehicle.toObject(includeInstance, f),
      transportcompany: (f = msg.getTransportcompany()) && Transport_pb.TransportCompany.toObject(includeInstance, f),
      store: (f = msg.getStore()) && stores_pb.Store.toObject(includeInstance, f),
      driver: (f = msg.getDriver()) && Transport_pb.Driver.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Route}
 */
proto.Route.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Route;
  return proto.Route.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Route} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Route}
 */
proto.Route.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setId(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setName(value);
        break;
      case 3:
        var value = new proto.RoutePoint;
        reader.readMessage(value,proto.RoutePoint.deserializeBinaryFromReader);
        msg.addRouterpoints(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setDeliverydate(value);
        break;
      case 5:
        var value = new proto.OptimizationTask;
        reader.readMessage(value,proto.OptimizationTask.deserializeBinaryFromReader);
        msg.setOptimizationtask(value);
        break;
      case 6:
        var value = new Transport_pb.Vehicle;
        reader.readMessage(value,Transport_pb.Vehicle.deserializeBinaryFromReader);
        msg.setVehicle(value);
        break;
      case 7:
        var value = new Transport_pb.TransportCompany;
        reader.readMessage(value,Transport_pb.TransportCompany.deserializeBinaryFromReader);
        msg.setTransportcompany(value);
        break;
      case 8:
        var value = new stores_pb.Store;
        reader.readMessage(value,stores_pb.Store.deserializeBinaryFromReader);
        msg.setStore(value);
        break;
      case 9:
        var value = new Transport_pb.Driver;
        reader.readMessage(value,Transport_pb.Driver.deserializeBinaryFromReader);
        msg.setDriver(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Route.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Route.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Route} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Route.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
        1,
        f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
        2,
        f
    );
  }
  f = message.getRouterpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
        3,
        f,
        proto.RoutePoint.serializeBinaryToWriter
    );
  }
  f = message.getDeliverydate();
  if (f.length > 0) {
    writer.writeString(
        4,
        f
    );
  }
  f = message.getOptimizationtask();
  if (f != null) {
    writer.writeMessage(
        5,
        f,
        proto.OptimizationTask.serializeBinaryToWriter
    );
  }
  f = message.getVehicle();
  if (f != null) {
    writer.writeMessage(
        6,
        f,
        Transport_pb.Vehicle.serializeBinaryToWriter
    );
  }
  f = message.getTransportcompany();
  if (f != null) {
    writer.writeMessage(
        7,
        f,
        Transport_pb.TransportCompany.serializeBinaryToWriter
    );
  }
  f = message.getStore();
  if (f != null) {
    writer.writeMessage(
        8,
        f,
        stores_pb.Store.serializeBinaryToWriter
    );
  }
  f = message.getDriver();
  if (f != null) {
    writer.writeMessage(
        9,
        f,
        Transport_pb.Driver.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Route.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.Route.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Route.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.Route.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated RoutePoint routerPoints = 3;
 * @return {!Array<!proto.RoutePoint>}
 */
proto.Route.prototype.getRouterpointsList = function() {
  return /** @type{!Array<!proto.RoutePoint>} */ (
      jspb.Message.getRepeatedWrapperField(this, proto.RoutePoint, 3));
};


/** @param {!Array<!proto.RoutePoint>} value */
proto.Route.prototype.setRouterpointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.RoutePoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.RoutePoint}
 */
proto.Route.prototype.addRouterpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.RoutePoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Route.prototype.clearRouterpointsList = function() {
  this.setRouterpointsList([]);
};


/**
 * optional string deliveryDate = 4;
 * @return {string}
 */
proto.Route.prototype.getDeliverydate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.Route.prototype.setDeliverydate = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional OptimizationTask optimizationTask = 5;
 * @return {?proto.OptimizationTask}
 */
proto.Route.prototype.getOptimizationtask = function() {
  return /** @type{?proto.OptimizationTask} */ (
      jspb.Message.getWrapperField(this, proto.OptimizationTask, 5));
};


/** @param {?proto.OptimizationTask|undefined} value */
proto.Route.prototype.setOptimizationtask = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Route.prototype.clearOptimizationtask = function() {
  this.setOptimizationtask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Route.prototype.hasOptimizationtask = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Vehicle vehicle = 6;
 * @return {?proto.Vehicle}
 */
proto.Route.prototype.getVehicle = function() {
  return /** @type{?proto.Vehicle} */ (
      jspb.Message.getWrapperField(this, Transport_pb.Vehicle, 6));
};


/** @param {?proto.Vehicle|undefined} value */
proto.Route.prototype.setVehicle = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Route.prototype.clearVehicle = function() {
  this.setVehicle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Route.prototype.hasVehicle = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional TransportCompany transportCompany = 7;
 * @return {?proto.TransportCompany}
 */
proto.Route.prototype.getTransportcompany = function() {
  return /** @type{?proto.TransportCompany} */ (
      jspb.Message.getWrapperField(this, Transport_pb.TransportCompany, 7));
};


/** @param {?proto.TransportCompany|undefined} value */
proto.Route.prototype.setTransportcompany = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Route.prototype.clearTransportcompany = function() {
  this.setTransportcompany(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Route.prototype.hasTransportcompany = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Store store = 8;
 * @return {?proto.Store}
 */
proto.Route.prototype.getStore = function() {
  return /** @type{?proto.Store} */ (
      jspb.Message.getWrapperField(this, stores_pb.Store, 8));
};


/** @param {?proto.Store|undefined} value */
proto.Route.prototype.setStore = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Route.prototype.clearStore = function() {
  this.setStore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Route.prototype.hasStore = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional Driver driver = 9;
 * @return {?proto.Driver}
 */
proto.Route.prototype.getDriver = function() {
  return /** @type{?proto.Driver} */ (
      jspb.Message.getWrapperField(this, Transport_pb.Driver, 9));
};


/** @param {?proto.Driver|undefined} value */
proto.Route.prototype.setDriver = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Route.prototype.clearDriver = function() {
  this.setDriver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Route.prototype.hasDriver = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.RoutePoint.prototype.toObject = function(opt_includeInstance) {
    return proto.RoutePoint.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.RoutePoint} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.RoutePoint.toObject = function(includeInstance, msg) {
    var obj = {
      id: jspb.Message.getFieldWithDefault(msg, 1, 0),
      delivery: (f = msg.getDelivery()) && Delivery_pb.Delivery.toObject(includeInstance, f),
      arrivaltime: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
      pos: jspb.Message.getFieldWithDefault(msg, 4, 0)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.RoutePoint}
 */
proto.RoutePoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.RoutePoint;
  return proto.RoutePoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.RoutePoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.RoutePoint}
 */
proto.RoutePoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setId(value);
        break;
      case 2:
        var value = new Delivery_pb.Delivery;
        reader.readMessage(value,Delivery_pb.Delivery.deserializeBinaryFromReader);
        msg.setDelivery(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setArrivaltime(value);
        break;
      case 4:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setPos(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.RoutePoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.RoutePoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.RoutePoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.RoutePoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
        1,
        f
    );
  }
  f = message.getDelivery();
  if (f != null) {
    writer.writeMessage(
        2,
        f,
        Delivery_pb.Delivery.serializeBinaryToWriter
    );
  }
  f = message.getArrivaltime();
  if (f !== 0.0) {
    writer.writeDouble(
        3,
        f
    );
  }
  f = message.getPos();
  if (f !== 0) {
    writer.writeInt32(
        4,
        f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.RoutePoint.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.RoutePoint.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Delivery delivery = 2;
 * @return {?proto.Delivery}
 */
proto.RoutePoint.prototype.getDelivery = function() {
  return /** @type{?proto.Delivery} */ (
      jspb.Message.getWrapperField(this, Delivery_pb.Delivery, 2));
};


/** @param {?proto.Delivery|undefined} value */
proto.RoutePoint.prototype.setDelivery = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.RoutePoint.prototype.clearDelivery = function() {
  this.setDelivery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.RoutePoint.prototype.hasDelivery = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double arrivalTime = 3;
 * @return {number}
 */
proto.RoutePoint.prototype.getArrivaltime = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.RoutePoint.prototype.setArrivaltime = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 pos = 4;
 * @return {number}
 */
proto.RoutePoint.prototype.getPos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.RoutePoint.prototype.setPos = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.OptimizationTask.repeatedFields_ = [5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.OptimizationTask.prototype.toObject = function(opt_includeInstance) {
    return proto.OptimizationTask.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.OptimizationTask} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.OptimizationTask.toObject = function(includeInstance, msg) {
    var obj = {
      id: jspb.Message.getFieldWithDefault(msg, 1, 0),
      createdatetime: jspb.Message.getFieldWithDefault(msg, 2, ""),
      startdatetime: jspb.Message.getFieldWithDefault(msg, 3, ""),
      completedatetime: jspb.Message.getFieldWithDefault(msg, 4, ""),
      deliveriesList: jspb.Message.toObjectList(msg.getDeliveriesList(),
          Delivery_pb.Delivery.toObject, includeInstance),
      vehiclesList: jspb.Message.toObjectList(msg.getVehiclesList(),
          Transport_pb.Vehicle.toObject, includeInstance),
      itemsList: jspb.Message.toObjectList(msg.getItemsList(),
          proto.Route.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.OptimizationTask}
 */
proto.OptimizationTask.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.OptimizationTask;
  return proto.OptimizationTask.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.OptimizationTask} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.OptimizationTask}
 */
proto.OptimizationTask.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setId(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCreatedatetime(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setStartdatetime(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setCompletedatetime(value);
        break;
      case 5:
        var value = new Delivery_pb.Delivery;
        reader.readMessage(value,Delivery_pb.Delivery.deserializeBinaryFromReader);
        msg.addDeliveries(value);
        break;
      case 6:
        var value = new Transport_pb.Vehicle;
        reader.readMessage(value,Transport_pb.Vehicle.deserializeBinaryFromReader);
        msg.addVehicles(value);
        break;
      case 7:
        var value = new proto.Route;
        reader.readMessage(value,proto.Route.deserializeBinaryFromReader);
        msg.addItems(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.OptimizationTask.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.OptimizationTask.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.OptimizationTask} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OptimizationTask.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
        1,
        f
    );
  }
  f = message.getCreatedatetime();
  if (f.length > 0) {
    writer.writeString(
        2,
        f
    );
  }
  f = message.getStartdatetime();
  if (f.length > 0) {
    writer.writeString(
        3,
        f
    );
  }
  f = message.getCompletedatetime();
  if (f.length > 0) {
    writer.writeString(
        4,
        f
    );
  }
  f = message.getDeliveriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
        5,
        f,
        Delivery_pb.Delivery.serializeBinaryToWriter
    );
  }
  f = message.getVehiclesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
        6,
        f,
        Transport_pb.Vehicle.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
        7,
        f,
        proto.Route.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.OptimizationTask.OptimizationTaskStatusEnum = {
  NEW: 0,
  STARTED: 1,
  CANCELED: 2,
  SOLVED: 3,
  PARTIAL_SOLVED: 4,
  UNFEASIBLE: 5
};

/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.OptimizationTask.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.OptimizationTask.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string createDateTime = 2;
 * @return {string}
 */
proto.OptimizationTask.prototype.getCreatedatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.OptimizationTask.prototype.setCreatedatetime = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string startDateTime = 3;
 * @return {string}
 */
proto.OptimizationTask.prototype.getStartdatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.OptimizationTask.prototype.setStartdatetime = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string completeDateTime = 4;
 * @return {string}
 */
proto.OptimizationTask.prototype.getCompletedatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.OptimizationTask.prototype.setCompletedatetime = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated Delivery deliveries = 5;
 * @return {!Array<!proto.Delivery>}
 */
proto.OptimizationTask.prototype.getDeliveriesList = function() {
  return /** @type{!Array<!proto.Delivery>} */ (
      jspb.Message.getRepeatedWrapperField(this, Delivery_pb.Delivery, 5));
};


/** @param {!Array<!proto.Delivery>} value */
proto.OptimizationTask.prototype.setDeliveriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.Delivery=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Delivery}
 */
proto.OptimizationTask.prototype.addDeliveries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.Delivery, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.OptimizationTask.prototype.clearDeliveriesList = function() {
  this.setDeliveriesList([]);
};


/**
 * repeated Vehicle vehicles = 6;
 * @return {!Array<!proto.Vehicle>}
 */
proto.OptimizationTask.prototype.getVehiclesList = function() {
  return /** @type{!Array<!proto.Vehicle>} */ (
      jspb.Message.getRepeatedWrapperField(this, Transport_pb.Vehicle, 6));
};


/** @param {!Array<!proto.Vehicle>} value */
proto.OptimizationTask.prototype.setVehiclesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.Vehicle=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Vehicle}
 */
proto.OptimizationTask.prototype.addVehicles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.Vehicle, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.OptimizationTask.prototype.clearVehiclesList = function() {
  this.setVehiclesList([]);
};


/**
 * repeated Route items = 7;
 * @return {!Array<!proto.Route>}
 */
proto.OptimizationTask.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.Route>} */ (
      jspb.Message.getRepeatedWrapperField(this, proto.Route, 7));
};


/** @param {!Array<!proto.Route>} value */
proto.OptimizationTask.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Route=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Route}
 */
proto.OptimizationTask.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Route, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.OptimizationTask.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.RouteAllResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.RouteAllResponse.prototype.toObject = function(opt_includeInstance) {
    return proto.RouteAllResponse.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.RouteAllResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.RouteAllResponse.toObject = function(includeInstance, msg) {
    var obj = {
      routesList: jspb.Message.toObjectList(msg.getRoutesList(),
          proto.Route.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.RouteAllResponse}
 */
proto.RouteAllResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.RouteAllResponse;
  return proto.RouteAllResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.RouteAllResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.RouteAllResponse}
 */
proto.RouteAllResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.Route;
        reader.readMessage(value,proto.Route.deserializeBinaryFromReader);
        msg.addRoutes(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.RouteAllResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.RouteAllResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.RouteAllResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.RouteAllResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoutesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
        1,
        f,
        proto.Route.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Route routes = 1;
 * @return {!Array<!proto.Route>}
 */
proto.RouteAllResponse.prototype.getRoutesList = function() {
  return /** @type{!Array<!proto.Route>} */ (
      jspb.Message.getRepeatedWrapperField(this, proto.Route, 1));
};


/** @param {!Array<!proto.Route>} value */
proto.RouteAllResponse.prototype.setRoutesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Route=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Route}
 */
proto.RouteAllResponse.prototype.addRoutes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Route, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.RouteAllResponse.prototype.clearRoutesList = function() {
  this.setRoutesList([]);
};


goog.object.extend(exports, proto);
